### ISSUE TITLE
Problem with step "Generate CSR" when using own keys

### ISSUE THREAD

**Issue by pachulo** [4ARMED/ansible-burp-collaborator#1]
Hi! First of all thanks for creating this role!

Now, I'm using your role to deploy burp-collaborator and observed that, when using my own certificates, the "Generate CSR" step in the main task fails, because burp.key does not exist. The only files that exists are:

- PKCS8 private key
- Certificate
- Intermediate certificate

I've added "generate_self_signed_certs" to "when" like this:

```
- name: Generate CSR
  command: openssl req -new -key burp.key -out burp.csr -subj "/C={{ country }}/ST={{ state }}/L={{ locality }}/O={{ organisation }}/OU={{ organisational_unit }}/CN=*.{{ burp_server_domain }}"
  delegate_to: 127.0.0.1
  become: no
  when:
    - generate_self_signed_certs
    - not existing_csr.stat.exists

...

```

And then it works OK. Should it be that way?
